terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
  location = var.location
}

resource "azurerm_storage_account" "sa" {
  name                     = var.storage_account_name
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"

  static_website {
    index_document     = "index.html"
    error_404_document = "index.html"
  }
}

resource "azurerm_storage_table" "survey" {
  name                 = "survey"
  storage_account_name = azurerm_storage_account.sa.name
}

resource "azurerm_storage_table" "votes" {
  name                 = "votes"
  storage_account_name = azurerm_storage_account.sa.name
}

data "azurerm_storage_account_sas" "sas" {
  connection_string = azurerm_storage_account.sa.primary_connection_string
  https_only        = true

  resource_types {
    service   = true
    container = true
    object    = true
  }

  services {
    blob  = false
    queue = false
    table = true
    file  = false
  }

  start  = var.sas_start
  expiry = var.sas_expiry

  permissions {
    read    = true
    write   = true
    delete  = true
    list    = true
    add     = true
    create  = true
    update  = true
    process = false
    tag     = false
    filter  = false
  }
}

# Configure CORS on the Table service so the browser can call Table Storage
resource "null_resource" "table_cors" {
  depends_on = [azurerm_storage_account.sa]

  provisioner "local-exec" {
    command = <<-EOT
      az storage cors add \
        --services t \
        --methods GET POST PUT MERGE DELETE OPTIONS \
        --origins '*' \
        --allowed-headers '*' \
        --exposed-headers '*' \
        --max-age 3600
    EOT

    environment = {
      AZURE_STORAGE_ACCOUNT = azurerm_storage_account.sa.name
      AZURE_STORAGE_KEY     = azurerm_storage_account.sa.primary_access_key
    }
  }
}

# Generate config.js with real values from Terraform
resource "local_file" "config_js" {
  filename = "${path.module}/../frontend/js/config.js"
  content  = <<-EOT
    // Auto-generated by Terraform — do not edit manually.
    const CONFIG = {
      storageAccount: "${azurerm_storage_account.sa.name}",
      sasToken: "${data.azurerm_storage_account_sas.sas.sas}",
      passcode: "${var.app_passcode}",
      adminCode: "${var.admin_code}"
    };
  EOT
}

# Upload all frontend files to the $web blob container
resource "null_resource" "upload_frontend" {
  depends_on = [
    azurerm_storage_account.sa,
    local_file.config_js
  ]

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command = <<-EOT
      az storage blob upload-batch \
        --destination '$web' \
        --source ${path.module}/../frontend \
        --overwrite
    EOT

    environment = {
      AZURE_STORAGE_ACCOUNT = azurerm_storage_account.sa.name
      AZURE_STORAGE_KEY     = azurerm_storage_account.sa.primary_access_key
    }
  }
}
