// Auto-generated by Terraform — do not edit manually.
const CONFIG = {
  storageAccount: "rcvapp2026",
  sasToken: "?sv=2017-07-29&ss=t&srt=sco&sp=rwdlacu&se=2027-12-31T23:59:59Z&st=2025-01-01T00:00:00Z&spr=https&sig=64r6mXneKfrrXYEAxCWHGZDcgZD0WQnlCJzFcKb76vU%3D",
  passcode: "songsforthebarn",
  adminCode: "createsongsforthebarn"
};
