// Auto-generated by Terraform — do not edit manually.
// Values are base64-encoded to discourage casual inspection.
var _E = {
  storageAccount: "cmN2YXBwMjAyNg==",
  sasToken: "P3N2PTIwMTctMDctMjkmc3M9dCZzcnQ9c2NvJnNwPXJ3ZGxhY3Umc2U9MjAyNy0xMi0zMVQyMzo1OTo1OVomc3Q9MjAyNS0wMS0wMVQwMDowMDowMFomc3ByPWh0dHBzJnNpZz02NHI2bVhuZUtmcnJYWUVBeENXSEdaRGNnWkQwV1FubENKekZjS2I3NnZVJTNE",
  passcode: "c29uZ3Nmb3J0aGViYXJu",
  adminCode: "Y3JlYXRlc29uZ3Nmb3J0aGViYXJu"
};
var CONFIG = {};
Object.keys(_E).forEach(function (k) { CONFIG[k] = atob(_E[k]); });
